spring.application.name=testBoard

# MySQL ?? ?? (board_db ??? DBeaver?? ??? ???? ????)
spring.datasource.url=jdbc:mysql://localhost:3306/testBoard?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=1234

# ???? SQL? ???? ??? ??? (??? ? ??!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ???? ?? ???? ???? ??/????? ??
spring.jpa.hibernate.ddl-auto=update